# Generated by Django 5.1.4 on 2025-01-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20230516_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ['-date']},
        ),
    ]
