# Generated by Django 5.1.4 on 2025-01-08 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_options_alter_kyc_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='kyc'),
        ),
    ]
