# Generated by Django 5.1.4 on 2025-01-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_recommended_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kyc_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='kyc_submitted',
            field=models.BooleanField(default=True),
        ),
    ]
