# Generated by Django 5.1.4 on 2025-01-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kyc_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='kyc_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
