# Generated by Django 5.1.4 on 2025-01-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_account_kyc_confirmed_and_more'),
        ('account', '0014_alter_account_user'),
    ]

    operations = [
    ]
