# Generated by Django 5.1.4 on 2025-01-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_merge_20250126_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
