# Generated by Django 5.1.4 on 2025-02-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_account_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.BooleanField(default=False),
        ),
    ]
