# Generated by Django 6.1.1 on 2026-09-28 14:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_received_transactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(default='TRC20', editable=False, max_length=20)),
                ('address', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Enter a valid-looking TRON wallet address.', regex='^T[1-9A-HJ-NP-Za-km-z]{33}$')])),
                ('changelly_url', models.URLField(default='https://changelly.com/buy')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paylio USDT receiving wallet',
                'verbose_name_plural': 'Paylio USDT receiving wallet',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('received', 'Received'), ('recieved', 'Recieved'), ('crypto_deposit', 'Crypto Deposit'), ('withdraw', 'withdraw'), ('refund', 'Refund'), ('request', 'Payment Request'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_payment_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('network', models.CharField(default='TRC20', editable=False, max_length=20)),
                ('wallet_address', models.CharField(max_length=128)),
                ('tx_hash', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('confirmed', 'Confirmed and credited'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crypto_deposit', to='core.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crypto_deposits', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_crypto_deposits', to=settings.AUTH_USER_MODEL)),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='core.paymentlink')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
