# Generated by Django 6.1.1 on 2026-09-28 14:56

import django.db.models.deletion
from django.db import migrations, models


def create_default_gateways(apps, schema_editor):
    CryptoPaymentGateway = apps.get_model("core", "CryptoPaymentGateway")
    gateways = {
        "changelly": "https://changelly.com/buy",
        "moonpay": "https://www.moonpay.com/buy",
        "transak": "https://global.transak.com/",
    }
    for gateway, buy_url in gateways.items():
        CryptoPaymentGateway.objects.using(schema_editor.connection.alias).get_or_create(
            gateway=gateway,
            defaults={"buy_url": buy_url},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cryptowallet_alter_notification_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('changelly', 'Changelly'), ('moonpay', 'MoonPay'), ('transak', 'Transak')], max_length=20, unique=True)),
                ('buy_url', models.URLField()),
                ('usd_per_usdt', models.DecimalField(blank=True, decimal_places=6, help_text='USD credited for each 1 USDT received.', max_digits=12, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'crypto payment gateway',
                'verbose_name_plural': 'crypto payment gateways',
                'ordering': ('gateway',),
            },
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='usd_per_usdt_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='core.cryptopaymentgateway'),
        ),
        migrations.RunPython(create_default_gateways, migrations.RunPython.noop),
    ]
