# Generated by Django 5.1.4 on 2025-05-13 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transaction_date_alter_transaction_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
