# Generated by Django 6.1.1 on 2026-09-28 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cryptopaymentgateway_cryptodeposit_usd_per_usdt_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopaymentgateway',
            name='usd_per_usdt',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='USD credited for each 1 USDT received.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
    ]
