# Generated by Django 6.1.1 on 2026-09-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cryptopaymentgateway_usd_per_usdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodeposit',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
